run:
  timeout: 10m
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gochecknoinits
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unused
    - err113
